// Code generated by cmd/cgo; DO NOT EDIT.

//line /Users/fengwenxuan/Desktop/Guide_to_Go/Go高级编程/CGO/hello/hello.go:1:1
package main

/*
#include <stdio.h>

static void SayHi(const char* s) {
	puts(s);
}
*/
import _ "unsafe"

func main() {
	( /*line :13:2*/_Cfunc_SayHi /*line :13:8*/)(( /*line :13:10*/_Cfunc_CString /*line :13:18*/)("Hello!\n"))
}